baseURL = "https://calcagno.blog/"
languageCode = "en-us"
title = "Santiago Calcagno"
theme = "blank"

[markup]
  [markup.highlight]
    noClasses = false

[menu]
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/santicalcagno"
  [[menu.main]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/santicalcagno"

[permalinks]
  posts = "/:slug"